CREATE TABLE `leads` (
	`id` text PRIMARY KEY NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`flow` text NOT NULL,
	`service` text NOT NULL,
	`city` text,
	`zip` text,
	`name` text NOT NULL,
	`phone` text NOT NULL,
	`email` text,
	`contact_method` text,
	`payload_json` text NOT NULL,
	`landing_page` text,
	`page_url` text,
	`referrer` text,
	`utm_source` text,
	`utm_medium` text,
	`utm_campaign` text,
	`utm_term` text,
	`utm_content` text,
	`channel` text,
	`score` integer NOT NULL,
	`score_label` text NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`consent` integer DEFAULT 0 NOT NULL
);
